#!/bin/bash          
#                    
cd /tmp/target/roivis_output1
find . -name '*' -print | zip Roivis.zip -@
cp Roivis.zip /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/roivis_output1/
find ./ -type f -print0 | xargs -0 rm -f
wait


