#!/bin/bash          
#                    
#!/bin/bash
mkdir -p /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/03_registration/02_air_lddmm/atlas_3/1_histmatch
mkdir -p /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/03_registration/02_air_lddmm/atlas_3/4_deformations
#!/bin/bash	    
#		    
/work/00303/tg455757/stampede2/M1_101214/scripts_070218/AIR_LDDMM_ver07a.pl 1 2 0 /work/00303/tg455757/stampede2/M1_101214/atlassets/atlassetupdate_083014/1_05_MNI.img /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/02_inhomogcorrection/target.img 1 1 /work/00303/tg455757/stampede2/M1_101214/atlassets/atlassetupdate_083014/1_05_7L.img /work/00303/tg455757/stampede2/M1_101214/atlassets/atlassetupdate_083014/FT5L/FT5l_105.img /tmp/target/03_registration/02_air_lddmm/atlas_3 2 0 2 0.5 1
cp -R /tmp/target/03_registration/02_air_lddmm/atlas_3/1_histmatch/*.img /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/03_registration/02_air_lddmm/atlas_3/1_histmatch/
cp -R /tmp/target/03_registration/02_air_lddmm/atlas_3/1_histmatch/*.hdr /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/03_registration/02_air_lddmm/atlas_3/1_histmatch/
cp -R /tmp/target/03_registration/02_air_lddmm/atlas_3/4_deformations/*  /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/03_registration/02_air_lddmm/atlas_3/4_deformations/
rm -fr /tmp/target/03_registration/02_air_lddmm/atlas_3/1_histmatch/
rm -fr /tmp/target/03_registration/02_air_lddmm/atlas_3/4_deformations/
rm -fr /tmp/target/03_registration/02_air_lddmm/atlas_3/3_lddmm/

#!/bin/bash          
#                    
#!/bin/bash
mkdir -p /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/03_registration/02_air_lddmm/atlas_9/1_histmatch
mkdir -p /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/03_registration/02_air_lddmm/atlas_9/4_deformations
#!/bin/bash	    
#		    
/work/00303/tg455757/stampede2/M1_101214/scripts_070218/AIR_LDDMM_ver07a.pl 1 2 0 /work/00303/tg455757/stampede2/M1_101214/atlassets/atlassetupdate_083014/GSK_NC_800005.img /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/02_inhomogcorrection/target.img 1 1 /work/00303/tg455757/stampede2/M1_101214/atlassets/atlassetupdate_083014/800005_7L.img /work/00303/tg455757/stampede2/M1_101214/atlassets/atlassetupdate_083014/FT5L/FT5l_GSK_NC_800005.img /tmp/target/03_registration/02_air_lddmm/atlas_9 2 0 2 0.5 1
cp -R /tmp/target/03_registration/02_air_lddmm/atlas_9/1_histmatch/*.img /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/03_registration/02_air_lddmm/atlas_9/1_histmatch/
cp -R /tmp/target/03_registration/02_air_lddmm/atlas_9/1_histmatch/*.hdr /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/03_registration/02_air_lddmm/atlas_9/1_histmatch/
cp -R /tmp/target/03_registration/02_air_lddmm/atlas_9/4_deformations/*  /home1/02684/lddmmpro/process_queue/daeff36ba38bba9534eeb1e9e0c6b72b/registered/allAtlases/03_registration/02_air_lddmm/atlas_9/4_deformations/
rm -fr /tmp/target/03_registration/02_air_lddmm/atlas_9/1_histmatch/
rm -fr /tmp/target/03_registration/02_air_lddmm/atlas_9/4_deformations/
rm -fr /tmp/target/03_registration/02_air_lddmm/atlas_9/3_lddmm/

